### ISSUE TITLE
hundrumPosition missing in thisSpine.stream.flatten()

### ISSUE THREAD

**Issue by Dazzid** [cuthbertLab/music21#1462]
**music21 version**
`8.1.0`   

**Problem summary**
Loading a krn format into music21 and it get an error: 'Dynamic' object has no attribute 'humdrumPosition' 

**Steps to reproduce**
I just downloaded the sonata from the tutorial, https://wiki.ccarh.org/wiki/Music21:_Loading_a_Humdrum_file
```
work = converter.parse('sonata.krn')
work.show()
```

**Expected vs. actual behavior**
Not rendering the Sonata.

**More information**
Working on a Mac macOS Monterrey 12.2.1. M1 pro chip.

Actual error:
```
File ~/miniforge3/envs/myenv/lib/python3.10/site-packages/music21/humdrum/spineParser.py:1944, in SpineCollection.moveDynamicsAndLyricsToStreams(self)
   1942 for dynamic in thisSpine.stream.flatten():
   1943     if isinstance(dynamic, dynamics.Dynamic):
-> 1944         prioritiesToSearch[dynamic.humdrumPosition] = dynamic
   1945 for applyStaff in stavesAppliedTo:
   1946     applyStream = kernStreams[applyStaff]
```

**Comment by mscuthbert** [comment]
When I use the format in the Wiki as:

```
converter.parse('http://kern.ccarh.org/data?l=beethoven/sonatas&file=sonata01-1.krn')
```

it works for me in v8.1.  Same setup as you except Intel mac not M1.

Does accessing via URL work for you?  It's possible that the remainder of the instructions (not written by me) for downloading no longer work -- you can see that they're written for an old version of Python.  If accessing via URL works, then I'll close this and put a report in to the CCARH people.

Note that showing the file does not currently work in v9.0.0a4 master -- working on a fix now.

**Comment by Dazzid** [comment]
Thanks for the answer. You are right, accessing via URL is working well. We can close this
